---
apiVersion: v1

kind: Pod

metadata:
  name: redis
  namespace: default
  labels:
    app: nginx
    tier: db

spec:
  containers:
    - name: nginx-alpine-container
      image: nredis:alpine
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2
  #SchedulerName: XYZ
      envFrom:               #for ENV config map
        - configMapRef:
            name: app-config

      env:                  # For Single ENV
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              key: APP_COLOR
      
      volumes:
        - name:  app-config-volume
          configMap:
            name:  app-config
        mountPath:  Path to mount
  
  nodeName: node01

  tolerations:
    - key: "app"
      operator: "Equal"
      value: "Blue"
      effect: "NoScheule"

#======================================================================================================================================
---
apiVersion: v1

kind: Pod

metadata:
  name: redis
  namespace: finance
  labels:
    app: redis
    type: backend

spec:
  containers:
    - name: redis-container
      image: redis

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "size"
              operator: In | NotIn
              values:
                - Large