apiVersion: v1
kind: Pod
metadata:  creationTimestamp: "2020-01-11T15:01:21Z"
  labels:
    name: webapp-color
  name: webapp-color  namespace: default
  resourceVersion: "1186"
  selfLink: /api/v1/namespaces/default/pods/webapp-color
  uid: f3d18f28-9401-4da1-98c8-ccdaf3343262
spec:
  containers:
  - envFrom:
    - configMapRef:
        name: web-config-map
    image: kodekloud/webapp-color
    imagePullPolicy: Always
    name: webapp-color
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-d82k2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node01
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-d82k2
    secret:
      defaultMode: 420
      secretName: default-token-d82k2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-11T15:01:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-11T15:01:24Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-11T15:01:24Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-11T15:01:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a54db4c7ec36cf7c620c55945839669940faf57df9e54b1cc46a27299796f24e
    image: kodekloud/webapp-color:latest
    imageID: docker-pullable://kodekloud/webapp-color@sha256:99c3821ea49b89c7a22d3eebab5c2e1ec651452e7675af243485034a72eb1423
    lastState: {}
    name: webapp-color
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-01-11T15:01:23Z"
  hostIP: 172.17.0.15
  phase: Running
  podIP: 10.32.0.4
  podIPs:
  - ip: 10.32.0.4
  qosClass: BestEffort
  startTime: "2020-01-11T15:01:21Z"